//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppClient.CanchitaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarifa", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Tarifa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Checked {
            get {
                return this.CheckedField;
            }
            set {
                if ((this.CheckedField.Equals(value) != true)) {
                    this.CheckedField = value;
                    this.RaisePropertyChanged("Checked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinField, value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppClient.CanchitaWS.Campo campoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double diferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppClient.CanchitaWS.Usuario usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaReserva {
            get {
                return this.FechaReservaField;
            }
            set {
                if ((this.FechaReservaField.Equals(value) != true)) {
                    this.FechaReservaField = value;
                    this.RaisePropertyChanged("FechaReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppClient.CanchitaWS.Campo campo {
            get {
                return this.campoField;
            }
            set {
                if ((object.ReferenceEquals(this.campoField, value) != true)) {
                    this.campoField = value;
                    this.RaisePropertyChanged("campo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double diferencia {
            get {
                return this.diferenciaField;
            }
            set {
                if ((this.diferenciaField.Equals(value) != true)) {
                    this.diferenciaField = value;
                    this.RaisePropertyChanged("diferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaOperacion {
            get {
                return this.fechaOperacionField;
            }
            set {
                if ((this.fechaOperacionField.Equals(value) != true)) {
                    this.fechaOperacionField = value;
                    this.RaisePropertyChanged("fechaOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppClient.CanchitaWS.Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campo", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Campo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppClient.CanchitaWS.Sede SedeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppClient.CanchitaWS.Sede Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleReserva", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class DetalleReserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppClient.CanchitaWS.Reserva ReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppClient.CanchitaWS.Tarifa TarifaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinField, value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppClient.CanchitaWS.Reserva Reserva {
            get {
                return this.ReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservaField, value) != true)) {
                    this.ReservaField = value;
                    this.RaisePropertyChanged("Reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppClient.CanchitaWS.Tarifa Tarifa {
            get {
                return this.TarifaField;
            }
            set {
                if ((object.ReferenceEquals(this.TarifaField, value) != true)) {
                    this.TarifaField = value;
                    this.RaisePropertyChanged("Tarifa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarjeta", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Tarjeta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double saldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppClient.CanchitaWS.Usuario usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                if ((this.fechaCreacionField.Equals(value) != true)) {
                    this.fechaCreacionField = value;
                    this.RaisePropertyChanged("fechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                if ((this.fechaVencimientoField.Equals(value) != true)) {
                    this.fechaVencimientoField = value;
                    this.RaisePropertyChanged("fechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idTarjeta {
            get {
                return this.idTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.idTarjetaField, value) != true)) {
                    this.idTarjetaField = value;
                    this.RaisePropertyChanged("idTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppClient.CanchitaWS.Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppClient.CanchitaWS.Reserva idReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nroPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppClient.CanchitaWS.Reserva idReserva {
            get {
                return this.idReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.idReservaField, value) != true)) {
                    this.idReservaField = value;
                    this.RaisePropertyChanged("idReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroPago {
            get {
                return this.nroPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.nroPagoField, value) != true)) {
                    this.nroPagoField = value;
                    this.RaisePropertyChanged("nroPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleReservaCompletoxUsuario", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class DetalleReservaCompletoxUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionCampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string horaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string horaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imagencampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double tarifaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCampo {
            get {
                return this.DescripcionCampoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionCampoField, value) != true)) {
                    this.DescripcionCampoField = value;
                    this.RaisePropertyChanged("DescripcionCampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionSede {
            get {
                return this.DescripcionSedeField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionSedeField, value) != true)) {
                    this.DescripcionSedeField = value;
                    this.RaisePropertyChanged("DescripcionSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionSede {
            get {
                return this.DireccionSedeField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionSedeField, value) != true)) {
                    this.DireccionSedeField = value;
                    this.RaisePropertyChanged("DireccionSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string horaFin {
            get {
                return this.horaFinField;
            }
            set {
                if ((object.ReferenceEquals(this.horaFinField, value) != true)) {
                    this.horaFinField = value;
                    this.RaisePropertyChanged("horaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.horaInicioField, value) != true)) {
                    this.horaInicioField = value;
                    this.RaisePropertyChanged("horaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] imagencampo {
            get {
                return this.imagencampoField;
            }
            set {
                if ((object.ReferenceEquals(this.imagencampoField, value) != true)) {
                    this.imagencampoField = value;
                    this.RaisePropertyChanged("imagencampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double tarifa {
            get {
                return this.tarifaField;
            }
            set {
                if ((this.tarifaField.Equals(value) != true)) {
                    this.tarifaField = value;
                    this.RaisePropertyChanged("tarifa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteReservasAnio", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class ReporteReservasAnio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes {
            get {
                return this.MesField;
            }
            set {
                if ((object.ReferenceEquals(this.MesField, value) != true)) {
                    this.MesField = value;
                    this.RaisePropertyChanged("Mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CanchitaWS.ITransaccion")]
    public interface ITransaccion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarUsuario", ReplyAction="http://tempuri.org/ITransaccion/AgregarUsuarioResponse")]
        bool AgregarUsuario(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarUsuario", ReplyAction="http://tempuri.org/ITransaccion/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> AgregarUsuarioAsync(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ActualizarUsuarioResponse")]
        bool ActualizarUsuario(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ListarUsuarioResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Usuario> ListarUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ListarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Usuario>> ListarUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EmininarUsuario", ReplyAction="http://tempuri.org/ITransaccion/EmininarUsuarioResponse")]
        bool EmininarUsuario(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EmininarUsuario", ReplyAction="http://tempuri.org/ITransaccion/EmininarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EmininarUsuarioAsync(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ValidarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ValidarUsuarioResponse")]
        AppClient.CanchitaWS.Usuario ValidarUsuario(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ValidarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<AppClient.CanchitaWS.Usuario> ValidarUsuarioAsync(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerUsuarioId", ReplyAction="http://tempuri.org/ITransaccion/ObtenerUsuarioIdResponse")]
        AppClient.CanchitaWS.Usuario ObtenerUsuarioId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerUsuarioId", ReplyAction="http://tempuri.org/ITransaccion/ObtenerUsuarioIdResponse")]
        System.Threading.Tasks.Task<AppClient.CanchitaWS.Usuario> ObtenerUsuarioIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/devolverUseryContra", ReplyAction="http://tempuri.org/ITransaccion/devolverUseryContraResponse")]
        AppClient.CanchitaWS.Usuario devolverUseryContra(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/devolverUseryContra", ReplyAction="http://tempuri.org/ITransaccion/devolverUseryContraResponse")]
        System.Threading.Tasks.Task<AppClient.CanchitaWS.Usuario> devolverUseryContraAsync(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/mandarCorreo", ReplyAction="http://tempuri.org/ITransaccion/mandarCorreoResponse")]
        string mandarCorreo(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/mandarCorreo", ReplyAction="http://tempuri.org/ITransaccion/mandarCorreoResponse")]
        System.Threading.Tasks.Task<string> mandarCorreoAsync(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/MensajeBienvenida", ReplyAction="http://tempuri.org/ITransaccion/MensajeBienvenidaResponse")]
        string MensajeBienvenida(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/MensajeBienvenida", ReplyAction="http://tempuri.org/ITransaccion/MensajeBienvenidaResponse")]
        System.Threading.Tasks.Task<string> MensajeBienvenidaAsync(AppClient.CanchitaWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarTarifas", ReplyAction="http://tempuri.org/ITransaccion/ListarTarifasResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Tarifa> ListarTarifas(System.DateTime fechaReserva, int idCampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarTarifas", ReplyAction="http://tempuri.org/ITransaccion/ListarTarifasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Tarifa>> ListarTarifasAsync(System.DateTime fechaReserva, int idCampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarTarifa", ReplyAction="http://tempuri.org/ITransaccion/AgregarTarifaResponse")]
        bool AgregarTarifa(AppClient.CanchitaWS.Tarifa tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarTarifa", ReplyAction="http://tempuri.org/ITransaccion/AgregarTarifaResponse")]
        System.Threading.Tasks.Task<bool> AgregarTarifaAsync(AppClient.CanchitaWS.Tarifa tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarTarifa", ReplyAction="http://tempuri.org/ITransaccion/EliminarTarifaResponse")]
        bool EliminarTarifa(AppClient.CanchitaWS.Tarifa tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarTarifa", ReplyAction="http://tempuri.org/ITransaccion/EliminarTarifaResponse")]
        System.Threading.Tasks.Task<bool> EliminarTarifaAsync(AppClient.CanchitaWS.Tarifa tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarTarifa", ReplyAction="http://tempuri.org/ITransaccion/ActualizarTarifaResponse")]
        bool ActualizarTarifa(AppClient.CanchitaWS.Tarifa tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarTarifa", ReplyAction="http://tempuri.org/ITransaccion/ActualizarTarifaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarTarifaAsync(AppClient.CanchitaWS.Tarifa tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarTarifasAdmin", ReplyAction="http://tempuri.org/ITransaccion/ListarTarifasAdminResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Tarifa> ListarTarifasAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarTarifasAdmin", ReplyAction="http://tempuri.org/ITransaccion/ListarTarifasAdminResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Tarifa>> ListarTarifasAdminAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerTarifaxI", ReplyAction="http://tempuri.org/ITransaccion/ObtenerTarifaxIResponse")]
        AppClient.CanchitaWS.Tarifa ObtenerTarifaxI(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerTarifaxI", ReplyAction="http://tempuri.org/ITransaccion/ObtenerTarifaxIResponse")]
        System.Threading.Tasks.Task<AppClient.CanchitaWS.Tarifa> ObtenerTarifaxIAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarReserva", ReplyAction="http://tempuri.org/ITransaccion/AgregarReservaResponse")]
        bool AgregarReserva(AppClient.CanchitaWS.Reserva reserva, System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReserva> listaDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarReserva", ReplyAction="http://tempuri.org/ITransaccion/AgregarReservaResponse")]
        System.Threading.Tasks.Task<bool> AgregarReservaAsync(AppClient.CanchitaWS.Reserva reserva, System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReserva> listaDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/retornarMontoReserva", ReplyAction="http://tempuri.org/ITransaccion/retornarMontoReservaResponse")]
        double retornarMontoReserva(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/retornarMontoReserva", ReplyAction="http://tempuri.org/ITransaccion/retornarMontoReservaResponse")]
        System.Threading.Tasks.Task<double> retornarMontoReservaAsync(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/obtenerUltimoIDReseva", ReplyAction="http://tempuri.org/ITransaccion/obtenerUltimoIDResevaResponse")]
        int obtenerUltimoIDReseva();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/obtenerUltimoIDReseva", ReplyAction="http://tempuri.org/ITransaccion/obtenerUltimoIDResevaResponse")]
        System.Threading.Tasks.Task<int> obtenerUltimoIDResevaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarReservaXUsuario", ReplyAction="http://tempuri.org/ITransaccion/listarReservaXUsuarioResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Reserva> listarReservaXUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarReservaXUsuario", ReplyAction="http://tempuri.org/ITransaccion/listarReservaXUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Reserva>> listarReservaXUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarReservas", ReplyAction="http://tempuri.org/ITransaccion/ListarReservasResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Reserva> ListarReservas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarReservas", ReplyAction="http://tempuri.org/ITransaccion/ListarReservasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Reserva>> ListarReservasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarReservasPendientes", ReplyAction="http://tempuri.org/ITransaccion/listarReservasPendientesResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Reserva> listarReservasPendientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarReservasPendientes", ReplyAction="http://tempuri.org/ITransaccion/listarReservasPendientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Reserva>> listarReservasPendientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarReservasCanceladas", ReplyAction="http://tempuri.org/ITransaccion/listarReservasCanceladasResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Reserva> listarReservasCanceladas(int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarReservasCanceladas", ReplyAction="http://tempuri.org/ITransaccion/listarReservasCanceladasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Reserva>> listarReservasCanceladasAsync(int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/verificar", ReplyAction="http://tempuri.org/ITransaccion/verificarResponse")]
        int verificar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/verificar", ReplyAction="http://tempuri.org/ITransaccion/verificarResponse")]
        System.Threading.Tasks.Task<int> verificarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/crearTarjetas", ReplyAction="http://tempuri.org/ITransaccion/crearTarjetasResponse")]
        bool crearTarjetas(AppClient.CanchitaWS.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/crearTarjetas", ReplyAction="http://tempuri.org/ITransaccion/crearTarjetasResponse")]
        System.Threading.Tasks.Task<bool> crearTarjetasAsync(AppClient.CanchitaWS.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/abonarSaldo", ReplyAction="http://tempuri.org/ITransaccion/abonarSaldoResponse")]
        bool abonarSaldo(AppClient.CanchitaWS.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/abonarSaldo", ReplyAction="http://tempuri.org/ITransaccion/abonarSaldoResponse")]
        System.Threading.Tasks.Task<bool> abonarSaldoAsync(AppClient.CanchitaWS.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarTarjetas", ReplyAction="http://tempuri.org/ITransaccion/listarTarjetasResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Tarjeta> listarTarjetas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarTarjetas", ReplyAction="http://tempuri.org/ITransaccion/listarTarjetasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Tarjeta>> listarTarjetasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerTarjetasXUsuario", ReplyAction="http://tempuri.org/ITransaccion/ObtenerTarjetasXUsuarioResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Tarjeta> ObtenerTarjetasXUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerTarjetasXUsuario", ReplyAction="http://tempuri.org/ITransaccion/ObtenerTarjetasXUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Tarjeta>> ObtenerTarjetasXUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/obtenerTarjeta", ReplyAction="http://tempuri.org/ITransaccion/obtenerTarjetaResponse")]
        AppClient.CanchitaWS.Tarjeta obtenerTarjeta(string idTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/obtenerTarjeta", ReplyAction="http://tempuri.org/ITransaccion/obtenerTarjetaResponse")]
        System.Threading.Tasks.Task<AppClient.CanchitaWS.Tarjeta> obtenerTarjetaAsync(string idTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/pagarReservaConTarjeta", ReplyAction="http://tempuri.org/ITransaccion/pagarReservaConTarjetaResponse")]
        bool pagarReservaConTarjeta(AppClient.CanchitaWS.Pago pago, string nroTarjeta, int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/pagarReservaConTarjeta", ReplyAction="http://tempuri.org/ITransaccion/pagarReservaConTarjetaResponse")]
        System.Threading.Tasks.Task<bool> pagarReservaConTarjetaAsync(AppClient.CanchitaWS.Pago pago, string nroTarjeta, int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarPagosPendientes", ReplyAction="http://tempuri.org/ITransaccion/listarPagosPendientesResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Pago> listarPagosPendientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarPagosPendientes", ReplyAction="http://tempuri.org/ITransaccion/listarPagosPendientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Pago>> listarPagosPendientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarPagosCancelados", ReplyAction="http://tempuri.org/ITransaccion/listarPagosCanceladosResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Pago> listarPagosCancelados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarPagosCancelados", ReplyAction="http://tempuri.org/ITransaccion/listarPagosCanceladosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Pago>> listarPagosCanceladosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/reservarPagoEfectivo", ReplyAction="http://tempuri.org/ITransaccion/reservarPagoEfectivoResponse")]
        bool reservarPagoEfectivo(AppClient.CanchitaWS.Pago pago, int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/reservarPagoEfectivo", ReplyAction="http://tempuri.org/ITransaccion/reservarPagoEfectivoResponse")]
        System.Threading.Tasks.Task<bool> reservarPagoEfectivoAsync(AppClient.CanchitaWS.Pago pago, int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/pagarReservaConEfectivo", ReplyAction="http://tempuri.org/ITransaccion/pagarReservaConEfectivoResponse")]
        bool pagarReservaConEfectivo(string nroPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/pagarReservaConEfectivo", ReplyAction="http://tempuri.org/ITransaccion/pagarReservaConEfectivoResponse")]
        System.Threading.Tasks.Task<bool> pagarReservaConEfectivoAsync(string nroPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarSede", ReplyAction="http://tempuri.org/ITransaccion/AgregarSedeResponse")]
        bool AgregarSede(AppClient.CanchitaWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarSede", ReplyAction="http://tempuri.org/ITransaccion/AgregarSedeResponse")]
        System.Threading.Tasks.Task<bool> AgregarSedeAsync(AppClient.CanchitaWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarSede", ReplyAction="http://tempuri.org/ITransaccion/ActualizarSedeResponse")]
        bool ActualizarSede(AppClient.CanchitaWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarSede", ReplyAction="http://tempuri.org/ITransaccion/ActualizarSedeResponse")]
        System.Threading.Tasks.Task<bool> ActualizarSedeAsync(AppClient.CanchitaWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarSedes", ReplyAction="http://tempuri.org/ITransaccion/ListarSedesResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Sede> ListarSedes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarSedes", ReplyAction="http://tempuri.org/ITransaccion/ListarSedesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Sede>> ListarSedesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarSede", ReplyAction="http://tempuri.org/ITransaccion/EliminarSedeResponse")]
        bool EliminarSede(AppClient.CanchitaWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarSede", ReplyAction="http://tempuri.org/ITransaccion/EliminarSedeResponse")]
        System.Threading.Tasks.Task<bool> EliminarSedeAsync(AppClient.CanchitaWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerSedeId", ReplyAction="http://tempuri.org/ITransaccion/ObtenerSedeIdResponse")]
        AppClient.CanchitaWS.Sede ObtenerSedeId(int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerSedeId", ReplyAction="http://tempuri.org/ITransaccion/ObtenerSedeIdResponse")]
        System.Threading.Tasks.Task<AppClient.CanchitaWS.Sede> ObtenerSedeIdAsync(int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarCampo", ReplyAction="http://tempuri.org/ITransaccion/AgregarCampoResponse")]
        bool AgregarCampo(AppClient.CanchitaWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarCampo", ReplyAction="http://tempuri.org/ITransaccion/AgregarCampoResponse")]
        System.Threading.Tasks.Task<bool> AgregarCampoAsync(AppClient.CanchitaWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarCampo", ReplyAction="http://tempuri.org/ITransaccion/ActualizarCampoResponse")]
        bool ActualizarCampo(AppClient.CanchitaWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarCampo", ReplyAction="http://tempuri.org/ITransaccion/ActualizarCampoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCampoAsync(AppClient.CanchitaWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarCampos", ReplyAction="http://tempuri.org/ITransaccion/ListarCamposResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Campo> ListarCampos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarCampos", ReplyAction="http://tempuri.org/ITransaccion/ListarCamposResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Campo>> ListarCamposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarCampo", ReplyAction="http://tempuri.org/ITransaccion/EliminarCampoResponse")]
        bool EliminarCampo(AppClient.CanchitaWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarCampo", ReplyAction="http://tempuri.org/ITransaccion/EliminarCampoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCampoAsync(AppClient.CanchitaWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerCamposXSede", ReplyAction="http://tempuri.org/ITransaccion/ObtenerCamposXSedeResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Campo> ObtenerCamposXSede(int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerCamposXSede", ReplyAction="http://tempuri.org/ITransaccion/ObtenerCamposXSedeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Campo>> ObtenerCamposXSedeAsync(int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerCamposXSede2", ReplyAction="http://tempuri.org/ITransaccion/ObtenerCamposXSede2Response")]
        System.Collections.Generic.List<AppClient.CanchitaWS.Campo> ObtenerCamposXSede2(int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerCamposXSede2", ReplyAction="http://tempuri.org/ITransaccion/ObtenerCamposXSede2Response")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Campo>> ObtenerCamposXSede2Async(int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerCamposXId", ReplyAction="http://tempuri.org/ITransaccion/ObtenerCamposXIdResponse")]
        AppClient.CanchitaWS.Campo ObtenerCamposXId(int idCampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerCamposXId", ReplyAction="http://tempuri.org/ITransaccion/ObtenerCamposXIdResponse")]
        System.Threading.Tasks.Task<AppClient.CanchitaWS.Campo> ObtenerCamposXIdAsync(int idCampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/verDetalleReserva", ReplyAction="http://tempuri.org/ITransaccion/verDetalleReservaResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReservaCompletoxUsuario> verDetalleReserva(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/verDetalleReserva", ReplyAction="http://tempuri.org/ITransaccion/verDetalleReservaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReservaCompletoxUsuario>> verDetalleReservaAsync(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarDetalleXReserva", ReplyAction="http://tempuri.org/ITransaccion/listarDetalleXReservaResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReserva> listarDetalleXReserva(int IdReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarDetalleXReserva", ReplyAction="http://tempuri.org/ITransaccion/listarDetalleXReservaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReserva>> listarDetalleXReservaAsync(int IdReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ReservasxAnio", ReplyAction="http://tempuri.org/ITransaccion/ReservasxAnioResponse")]
        System.Collections.Generic.List<AppClient.CanchitaWS.ReporteReservasAnio> ReservasxAnio(string anio, int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ReservasxAnio", ReplyAction="http://tempuri.org/ITransaccion/ReservasxAnioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.ReporteReservasAnio>> ReservasxAnioAsync(string anio, int idSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/retornarMontoAPagar", ReplyAction="http://tempuri.org/ITransaccion/retornarMontoAPagarResponse")]
        double retornarMontoAPagar(string nroPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/retornarMontoAPagar", ReplyAction="http://tempuri.org/ITransaccion/retornarMontoAPagarResponse")]
        System.Threading.Tasks.Task<double> retornarMontoAPagarAsync(string nroPago);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransaccionChannel : AppClient.CanchitaWS.ITransaccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransaccionClient : System.ServiceModel.ClientBase<AppClient.CanchitaWS.ITransaccion>, AppClient.CanchitaWS.ITransaccion {
        
        public TransaccionClient() {
        }
        
        public TransaccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransaccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AgregarUsuario(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.AgregarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarUsuarioAsync(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.AgregarUsuarioAsync(usuario);
        }
        
        public bool ActualizarUsuario(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.ActualizarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.ActualizarUsuarioAsync(usuario);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Usuario> ListarUsuario() {
            return base.Channel.ListarUsuario();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Usuario>> ListarUsuarioAsync() {
            return base.Channel.ListarUsuarioAsync();
        }
        
        public bool EmininarUsuario(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.EmininarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> EmininarUsuarioAsync(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.EmininarUsuarioAsync(usuario);
        }
        
        public AppClient.CanchitaWS.Usuario ValidarUsuario(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.ValidarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<AppClient.CanchitaWS.Usuario> ValidarUsuarioAsync(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.ValidarUsuarioAsync(usuario);
        }
        
        public AppClient.CanchitaWS.Usuario ObtenerUsuarioId(int id) {
            return base.Channel.ObtenerUsuarioId(id);
        }
        
        public System.Threading.Tasks.Task<AppClient.CanchitaWS.Usuario> ObtenerUsuarioIdAsync(int id) {
            return base.Channel.ObtenerUsuarioIdAsync(id);
        }
        
        public AppClient.CanchitaWS.Usuario devolverUseryContra(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.devolverUseryContra(usuario);
        }
        
        public System.Threading.Tasks.Task<AppClient.CanchitaWS.Usuario> devolverUseryContraAsync(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.devolverUseryContraAsync(usuario);
        }
        
        public string mandarCorreo(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.mandarCorreo(usuario);
        }
        
        public System.Threading.Tasks.Task<string> mandarCorreoAsync(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.mandarCorreoAsync(usuario);
        }
        
        public string MensajeBienvenida(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.MensajeBienvenida(usuario);
        }
        
        public System.Threading.Tasks.Task<string> MensajeBienvenidaAsync(AppClient.CanchitaWS.Usuario usuario) {
            return base.Channel.MensajeBienvenidaAsync(usuario);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Tarifa> ListarTarifas(System.DateTime fechaReserva, int idCampo) {
            return base.Channel.ListarTarifas(fechaReserva, idCampo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Tarifa>> ListarTarifasAsync(System.DateTime fechaReserva, int idCampo) {
            return base.Channel.ListarTarifasAsync(fechaReserva, idCampo);
        }
        
        public bool AgregarTarifa(AppClient.CanchitaWS.Tarifa tarifa) {
            return base.Channel.AgregarTarifa(tarifa);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarTarifaAsync(AppClient.CanchitaWS.Tarifa tarifa) {
            return base.Channel.AgregarTarifaAsync(tarifa);
        }
        
        public bool EliminarTarifa(AppClient.CanchitaWS.Tarifa tarifa) {
            return base.Channel.EliminarTarifa(tarifa);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarTarifaAsync(AppClient.CanchitaWS.Tarifa tarifa) {
            return base.Channel.EliminarTarifaAsync(tarifa);
        }
        
        public bool ActualizarTarifa(AppClient.CanchitaWS.Tarifa tarifa) {
            return base.Channel.ActualizarTarifa(tarifa);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarTarifaAsync(AppClient.CanchitaWS.Tarifa tarifa) {
            return base.Channel.ActualizarTarifaAsync(tarifa);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Tarifa> ListarTarifasAdmin() {
            return base.Channel.ListarTarifasAdmin();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Tarifa>> ListarTarifasAdminAsync() {
            return base.Channel.ListarTarifasAdminAsync();
        }
        
        public AppClient.CanchitaWS.Tarifa ObtenerTarifaxI(int id) {
            return base.Channel.ObtenerTarifaxI(id);
        }
        
        public System.Threading.Tasks.Task<AppClient.CanchitaWS.Tarifa> ObtenerTarifaxIAsync(int id) {
            return base.Channel.ObtenerTarifaxIAsync(id);
        }
        
        public bool AgregarReserva(AppClient.CanchitaWS.Reserva reserva, System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReserva> listaDetalle) {
            return base.Channel.AgregarReserva(reserva, listaDetalle);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarReservaAsync(AppClient.CanchitaWS.Reserva reserva, System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReserva> listaDetalle) {
            return base.Channel.AgregarReservaAsync(reserva, listaDetalle);
        }
        
        public double retornarMontoReserva(int idReserva) {
            return base.Channel.retornarMontoReserva(idReserva);
        }
        
        public System.Threading.Tasks.Task<double> retornarMontoReservaAsync(int idReserva) {
            return base.Channel.retornarMontoReservaAsync(idReserva);
        }
        
        public int obtenerUltimoIDReseva() {
            return base.Channel.obtenerUltimoIDReseva();
        }
        
        public System.Threading.Tasks.Task<int> obtenerUltimoIDResevaAsync() {
            return base.Channel.obtenerUltimoIDResevaAsync();
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Reserva> listarReservaXUsuario(int idUsuario) {
            return base.Channel.listarReservaXUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Reserva>> listarReservaXUsuarioAsync(int idUsuario) {
            return base.Channel.listarReservaXUsuarioAsync(idUsuario);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Reserva> ListarReservas() {
            return base.Channel.ListarReservas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Reserva>> ListarReservasAsync() {
            return base.Channel.ListarReservasAsync();
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Reserva> listarReservasPendientes() {
            return base.Channel.listarReservasPendientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Reserva>> listarReservasPendientesAsync() {
            return base.Channel.listarReservasPendientesAsync();
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Reserva> listarReservasCanceladas(int idSede) {
            return base.Channel.listarReservasCanceladas(idSede);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Reserva>> listarReservasCanceladasAsync(int idSede) {
            return base.Channel.listarReservasCanceladasAsync(idSede);
        }
        
        public int verificar() {
            return base.Channel.verificar();
        }
        
        public System.Threading.Tasks.Task<int> verificarAsync() {
            return base.Channel.verificarAsync();
        }
        
        public bool crearTarjetas(AppClient.CanchitaWS.Tarjeta tarjeta) {
            return base.Channel.crearTarjetas(tarjeta);
        }
        
        public System.Threading.Tasks.Task<bool> crearTarjetasAsync(AppClient.CanchitaWS.Tarjeta tarjeta) {
            return base.Channel.crearTarjetasAsync(tarjeta);
        }
        
        public bool abonarSaldo(AppClient.CanchitaWS.Tarjeta tarjeta) {
            return base.Channel.abonarSaldo(tarjeta);
        }
        
        public System.Threading.Tasks.Task<bool> abonarSaldoAsync(AppClient.CanchitaWS.Tarjeta tarjeta) {
            return base.Channel.abonarSaldoAsync(tarjeta);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Tarjeta> listarTarjetas() {
            return base.Channel.listarTarjetas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Tarjeta>> listarTarjetasAsync() {
            return base.Channel.listarTarjetasAsync();
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Tarjeta> ObtenerTarjetasXUsuario(int id) {
            return base.Channel.ObtenerTarjetasXUsuario(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Tarjeta>> ObtenerTarjetasXUsuarioAsync(int id) {
            return base.Channel.ObtenerTarjetasXUsuarioAsync(id);
        }
        
        public AppClient.CanchitaWS.Tarjeta obtenerTarjeta(string idTarjeta) {
            return base.Channel.obtenerTarjeta(idTarjeta);
        }
        
        public System.Threading.Tasks.Task<AppClient.CanchitaWS.Tarjeta> obtenerTarjetaAsync(string idTarjeta) {
            return base.Channel.obtenerTarjetaAsync(idTarjeta);
        }
        
        public bool pagarReservaConTarjeta(AppClient.CanchitaWS.Pago pago, string nroTarjeta, int idReserva) {
            return base.Channel.pagarReservaConTarjeta(pago, nroTarjeta, idReserva);
        }
        
        public System.Threading.Tasks.Task<bool> pagarReservaConTarjetaAsync(AppClient.CanchitaWS.Pago pago, string nroTarjeta, int idReserva) {
            return base.Channel.pagarReservaConTarjetaAsync(pago, nroTarjeta, idReserva);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Pago> listarPagosPendientes() {
            return base.Channel.listarPagosPendientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Pago>> listarPagosPendientesAsync() {
            return base.Channel.listarPagosPendientesAsync();
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Pago> listarPagosCancelados() {
            return base.Channel.listarPagosCancelados();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Pago>> listarPagosCanceladosAsync() {
            return base.Channel.listarPagosCanceladosAsync();
        }
        
        public bool reservarPagoEfectivo(AppClient.CanchitaWS.Pago pago, int idReserva) {
            return base.Channel.reservarPagoEfectivo(pago, idReserva);
        }
        
        public System.Threading.Tasks.Task<bool> reservarPagoEfectivoAsync(AppClient.CanchitaWS.Pago pago, int idReserva) {
            return base.Channel.reservarPagoEfectivoAsync(pago, idReserva);
        }
        
        public bool pagarReservaConEfectivo(string nroPago) {
            return base.Channel.pagarReservaConEfectivo(nroPago);
        }
        
        public System.Threading.Tasks.Task<bool> pagarReservaConEfectivoAsync(string nroPago) {
            return base.Channel.pagarReservaConEfectivoAsync(nroPago);
        }
        
        public bool AgregarSede(AppClient.CanchitaWS.Sede sede) {
            return base.Channel.AgregarSede(sede);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarSedeAsync(AppClient.CanchitaWS.Sede sede) {
            return base.Channel.AgregarSedeAsync(sede);
        }
        
        public bool ActualizarSede(AppClient.CanchitaWS.Sede sede) {
            return base.Channel.ActualizarSede(sede);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarSedeAsync(AppClient.CanchitaWS.Sede sede) {
            return base.Channel.ActualizarSedeAsync(sede);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Sede> ListarSedes() {
            return base.Channel.ListarSedes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Sede>> ListarSedesAsync() {
            return base.Channel.ListarSedesAsync();
        }
        
        public bool EliminarSede(AppClient.CanchitaWS.Sede sede) {
            return base.Channel.EliminarSede(sede);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarSedeAsync(AppClient.CanchitaWS.Sede sede) {
            return base.Channel.EliminarSedeAsync(sede);
        }
        
        public AppClient.CanchitaWS.Sede ObtenerSedeId(int idSede) {
            return base.Channel.ObtenerSedeId(idSede);
        }
        
        public System.Threading.Tasks.Task<AppClient.CanchitaWS.Sede> ObtenerSedeIdAsync(int idSede) {
            return base.Channel.ObtenerSedeIdAsync(idSede);
        }
        
        public bool AgregarCampo(AppClient.CanchitaWS.Campo campo) {
            return base.Channel.AgregarCampo(campo);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarCampoAsync(AppClient.CanchitaWS.Campo campo) {
            return base.Channel.AgregarCampoAsync(campo);
        }
        
        public bool ActualizarCampo(AppClient.CanchitaWS.Campo campo) {
            return base.Channel.ActualizarCampo(campo);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCampoAsync(AppClient.CanchitaWS.Campo campo) {
            return base.Channel.ActualizarCampoAsync(campo);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Campo> ListarCampos() {
            return base.Channel.ListarCampos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Campo>> ListarCamposAsync() {
            return base.Channel.ListarCamposAsync();
        }
        
        public bool EliminarCampo(AppClient.CanchitaWS.Campo campo) {
            return base.Channel.EliminarCampo(campo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCampoAsync(AppClient.CanchitaWS.Campo campo) {
            return base.Channel.EliminarCampoAsync(campo);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Campo> ObtenerCamposXSede(int idSede) {
            return base.Channel.ObtenerCamposXSede(idSede);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Campo>> ObtenerCamposXSedeAsync(int idSede) {
            return base.Channel.ObtenerCamposXSedeAsync(idSede);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.Campo> ObtenerCamposXSede2(int idSede) {
            return base.Channel.ObtenerCamposXSede2(idSede);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.Campo>> ObtenerCamposXSede2Async(int idSede) {
            return base.Channel.ObtenerCamposXSede2Async(idSede);
        }
        
        public AppClient.CanchitaWS.Campo ObtenerCamposXId(int idCampo) {
            return base.Channel.ObtenerCamposXId(idCampo);
        }
        
        public System.Threading.Tasks.Task<AppClient.CanchitaWS.Campo> ObtenerCamposXIdAsync(int idCampo) {
            return base.Channel.ObtenerCamposXIdAsync(idCampo);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReservaCompletoxUsuario> verDetalleReserva(int idReserva) {
            return base.Channel.verDetalleReserva(idReserva);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReservaCompletoxUsuario>> verDetalleReservaAsync(int idReserva) {
            return base.Channel.verDetalleReservaAsync(idReserva);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReserva> listarDetalleXReserva(int IdReserva) {
            return base.Channel.listarDetalleXReserva(IdReserva);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.DetalleReserva>> listarDetalleXReservaAsync(int IdReserva) {
            return base.Channel.listarDetalleXReservaAsync(IdReserva);
        }
        
        public System.Collections.Generic.List<AppClient.CanchitaWS.ReporteReservasAnio> ReservasxAnio(string anio, int idSede) {
            return base.Channel.ReservasxAnio(anio, idSede);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AppClient.CanchitaWS.ReporteReservasAnio>> ReservasxAnioAsync(string anio, int idSede) {
            return base.Channel.ReservasxAnioAsync(anio, idSede);
        }
        
        public double retornarMontoAPagar(string nroPago) {
            return base.Channel.retornarMontoAPagar(nroPago);
        }
        
        public System.Threading.Tasks.Task<double> retornarMontoAPagarAsync(string nroPago) {
            return base.Channel.retornarMontoAPagarAsync(nroPago);
        }
    }
}
