//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.33440
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canchita.PruebasUnitarias.TransaccionWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApMaterno {
            get {
                return this.ApMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApMaternoField, value) != true)) {
                    this.ApMaternoField = value;
                    this.RaisePropertyChanged("ApMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApPaterno {
            get {
                return this.ApPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApPaternoField, value) != true)) {
                    this.ApPaternoField = value;
                    this.RaisePropertyChanged("ApPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarifa", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Tarifa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Checked {
            get {
                return this.CheckedField;
            }
            set {
                if ((this.CheckedField.Equals(value) != true)) {
                    this.CheckedField = value;
                    this.RaisePropertyChanged("Checked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinField, value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Canchita.PruebasUnitarias.TransaccionWS.Campo campoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Canchita.PruebasUnitarias.TransaccionWS.Usuario usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaReserva {
            get {
                return this.FechaReservaField;
            }
            set {
                if ((this.FechaReservaField.Equals(value) != true)) {
                    this.FechaReservaField = value;
                    this.RaisePropertyChanged("FechaReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Canchita.PruebasUnitarias.TransaccionWS.Campo campo {
            get {
                return this.campoField;
            }
            set {
                if ((object.ReferenceEquals(this.campoField, value) != true)) {
                    this.campoField = value;
                    this.RaisePropertyChanged("campo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campo", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Campo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Canchita.PruebasUnitarias.TransaccionWS.Sede SedeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Canchita.PruebasUnitarias.TransaccionWS.Sede Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleReserva", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class DetalleReserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Canchita.PruebasUnitarias.TransaccionWS.Reserva ReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Canchita.PruebasUnitarias.TransaccionWS.Tarifa TarifaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinField, value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Canchita.PruebasUnitarias.TransaccionWS.Reserva Reserva {
            get {
                return this.ReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservaField, value) != true)) {
                    this.ReservaField = value;
                    this.RaisePropertyChanged("Reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Canchita.PruebasUnitarias.TransaccionWS.Tarifa Tarifa {
            get {
                return this.TarifaField;
            }
            set {
                if ((object.ReferenceEquals(this.TarifaField, value) != true)) {
                    this.TarifaField = value;
                    this.RaisePropertyChanged("Tarifa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarjeta", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Tarjeta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double saldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Canchita.PruebasUnitarias.TransaccionWS.Usuario usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                if ((this.fechaCreacionField.Equals(value) != true)) {
                    this.fechaCreacionField = value;
                    this.RaisePropertyChanged("fechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                if ((this.fechaVencimientoField.Equals(value) != true)) {
                    this.fechaVencimientoField = value;
                    this.RaisePropertyChanged("fechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idTarjeta {
            get {
                return this.idTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.idTarjetaField, value) != true)) {
                    this.idTarjetaField = value;
                    this.RaisePropertyChanged("idTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://schemas.datacontract.org/2004/07/Canchita.Service.Modelo")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Canchita.PruebasUnitarias.TransaccionWS.Reserva idReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nroPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Canchita.PruebasUnitarias.TransaccionWS.Reserva idReserva {
            get {
                return this.idReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.idReservaField, value) != true)) {
                    this.idReservaField = value;
                    this.RaisePropertyChanged("idReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroPago {
            get {
                return this.nroPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.nroPagoField, value) != true)) {
                    this.nroPagoField = value;
                    this.RaisePropertyChanged("nroPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransaccionWS.ITransaccion")]
    public interface ITransaccion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarUsuario", ReplyAction="http://tempuri.org/ITransaccion/AgregarUsuarioResponse")]
        bool AgregarUsuario(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarUsuario", ReplyAction="http://tempuri.org/ITransaccion/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> AgregarUsuarioAsync(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ActualizarUsuarioResponse")]
        bool ActualizarUsuario(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ListarUsuarioResponse")]
        System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Usuario> ListarUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ListarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Usuario>> ListarUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ValidarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ValidarUsuarioResponse")]
        bool ValidarUsuario(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ValidarUsuario", ReplyAction="http://tempuri.org/ITransaccion/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarTarifas", ReplyAction="http://tempuri.org/ITransaccion/ListarTarifasResponse")]
        System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarifa> ListarTarifas(System.DateTime fechaReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarTarifas", ReplyAction="http://tempuri.org/ITransaccion/ListarTarifasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarifa>> ListarTarifasAsync(System.DateTime fechaReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarReserva", ReplyAction="http://tempuri.org/ITransaccion/AgregarReservaResponse")]
        bool AgregarReserva(Canchita.PruebasUnitarias.TransaccionWS.Reserva reserva, System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.DetalleReserva> listaDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarReserva", ReplyAction="http://tempuri.org/ITransaccion/AgregarReservaResponse")]
        System.Threading.Tasks.Task<bool> AgregarReservaAsync(Canchita.PruebasUnitarias.TransaccionWS.Reserva reserva, System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.DetalleReserva> listaDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/retornarMontoReserva", ReplyAction="http://tempuri.org/ITransaccion/retornarMontoReservaResponse")]
        double retornarMontoReserva(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/retornarMontoReserva", ReplyAction="http://tempuri.org/ITransaccion/retornarMontoReservaResponse")]
        System.Threading.Tasks.Task<double> retornarMontoReservaAsync(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/crearTarjetas", ReplyAction="http://tempuri.org/ITransaccion/crearTarjetasResponse")]
        bool crearTarjetas(Canchita.PruebasUnitarias.TransaccionWS.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/crearTarjetas", ReplyAction="http://tempuri.org/ITransaccion/crearTarjetasResponse")]
        System.Threading.Tasks.Task<bool> crearTarjetasAsync(Canchita.PruebasUnitarias.TransaccionWS.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/abonarSaldo", ReplyAction="http://tempuri.org/ITransaccion/abonarSaldoResponse")]
        bool abonarSaldo(Canchita.PruebasUnitarias.TransaccionWS.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/abonarSaldo", ReplyAction="http://tempuri.org/ITransaccion/abonarSaldoResponse")]
        System.Threading.Tasks.Task<bool> abonarSaldoAsync(Canchita.PruebasUnitarias.TransaccionWS.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarTarjetas", ReplyAction="http://tempuri.org/ITransaccion/listarTarjetasResponse")]
        System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta> listarTarjetas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarTarjetas", ReplyAction="http://tempuri.org/ITransaccion/listarTarjetasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta>> listarTarjetasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerTarjetasXUsuario", ReplyAction="http://tempuri.org/ITransaccion/ObtenerTarjetasXUsuarioResponse")]
        System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta> ObtenerTarjetasXUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ObtenerTarjetasXUsuario", ReplyAction="http://tempuri.org/ITransaccion/ObtenerTarjetasXUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta>> ObtenerTarjetasXUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/obtenerTarjeta", ReplyAction="http://tempuri.org/ITransaccion/obtenerTarjetaResponse")]
        Canchita.PruebasUnitarias.TransaccionWS.Tarjeta obtenerTarjeta(string idTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/obtenerTarjeta", ReplyAction="http://tempuri.org/ITransaccion/obtenerTarjetaResponse")]
        System.Threading.Tasks.Task<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta> obtenerTarjetaAsync(string idTarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/pagarReservaConTarjeta", ReplyAction="http://tempuri.org/ITransaccion/pagarReservaConTarjetaResponse")]
        bool pagarReservaConTarjeta(Canchita.PruebasUnitarias.TransaccionWS.Pago pago, string nroTarjeta, int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/pagarReservaConTarjeta", ReplyAction="http://tempuri.org/ITransaccion/pagarReservaConTarjetaResponse")]
        System.Threading.Tasks.Task<bool> pagarReservaConTarjetaAsync(Canchita.PruebasUnitarias.TransaccionWS.Pago pago, string nroTarjeta, int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarPagosPendientes", ReplyAction="http://tempuri.org/ITransaccion/listarPagosPendientesResponse")]
        System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Pago> listarPagosPendientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarPagosPendientes", ReplyAction="http://tempuri.org/ITransaccion/listarPagosPendientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Pago>> listarPagosPendientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarPagosCancelados", ReplyAction="http://tempuri.org/ITransaccion/listarPagosCanceladosResponse")]
        System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Pago> listarPagosCancelados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/listarPagosCancelados", ReplyAction="http://tempuri.org/ITransaccion/listarPagosCanceladosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Pago>> listarPagosCanceladosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarSede", ReplyAction="http://tempuri.org/ITransaccion/AgregarSedeResponse")]
        bool AgregarSede(Canchita.PruebasUnitarias.TransaccionWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarSede", ReplyAction="http://tempuri.org/ITransaccion/AgregarSedeResponse")]
        System.Threading.Tasks.Task<bool> AgregarSedeAsync(Canchita.PruebasUnitarias.TransaccionWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarSede", ReplyAction="http://tempuri.org/ITransaccion/ActualizarSedeResponse")]
        bool ActualizarSede(Canchita.PruebasUnitarias.TransaccionWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarSede", ReplyAction="http://tempuri.org/ITransaccion/ActualizarSedeResponse")]
        System.Threading.Tasks.Task<bool> ActualizarSedeAsync(Canchita.PruebasUnitarias.TransaccionWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarSedes", ReplyAction="http://tempuri.org/ITransaccion/ListarSedesResponse")]
        System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Sede> ListarSedes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarSedes", ReplyAction="http://tempuri.org/ITransaccion/ListarSedesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Sede>> ListarSedesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarSede", ReplyAction="http://tempuri.org/ITransaccion/EliminarSedeResponse")]
        bool EliminarSede(Canchita.PruebasUnitarias.TransaccionWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarSede", ReplyAction="http://tempuri.org/ITransaccion/EliminarSedeResponse")]
        System.Threading.Tasks.Task<bool> EliminarSedeAsync(Canchita.PruebasUnitarias.TransaccionWS.Sede sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarCampo", ReplyAction="http://tempuri.org/ITransaccion/AgregarCampoResponse")]
        bool AgregarCampo(Canchita.PruebasUnitarias.TransaccionWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/AgregarCampo", ReplyAction="http://tempuri.org/ITransaccion/AgregarCampoResponse")]
        System.Threading.Tasks.Task<bool> AgregarCampoAsync(Canchita.PruebasUnitarias.TransaccionWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarCampo", ReplyAction="http://tempuri.org/ITransaccion/ActualizarCampoResponse")]
        bool ActualizarCampo(Canchita.PruebasUnitarias.TransaccionWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ActualizarCampo", ReplyAction="http://tempuri.org/ITransaccion/ActualizarCampoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCampoAsync(Canchita.PruebasUnitarias.TransaccionWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarCampos", ReplyAction="http://tempuri.org/ITransaccion/ListarCamposResponse")]
        System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Campo> ListarCampos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/ListarCampos", ReplyAction="http://tempuri.org/ITransaccion/ListarCamposResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Campo>> ListarCamposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarCampo", ReplyAction="http://tempuri.org/ITransaccion/EliminarCampoResponse")]
        bool EliminarCampo(Canchita.PruebasUnitarias.TransaccionWS.Campo campo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaccion/EliminarCampo", ReplyAction="http://tempuri.org/ITransaccion/EliminarCampoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCampoAsync(Canchita.PruebasUnitarias.TransaccionWS.Campo campo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransaccionChannel : Canchita.PruebasUnitarias.TransaccionWS.ITransaccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransaccionClient : System.ServiceModel.ClientBase<Canchita.PruebasUnitarias.TransaccionWS.ITransaccion>, Canchita.PruebasUnitarias.TransaccionWS.ITransaccion {
        
        public TransaccionClient() {
        }
        
        public TransaccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransaccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AgregarUsuario(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario) {
            return base.Channel.AgregarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarUsuarioAsync(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario) {
            return base.Channel.AgregarUsuarioAsync(usuario);
        }
        
        public bool ActualizarUsuario(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario) {
            return base.Channel.ActualizarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario) {
            return base.Channel.ActualizarUsuarioAsync(usuario);
        }
        
        public System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Usuario> ListarUsuario() {
            return base.Channel.ListarUsuario();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Usuario>> ListarUsuarioAsync() {
            return base.Channel.ListarUsuarioAsync();
        }
        
        public bool ValidarUsuario(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario) {
            return base.Channel.ValidarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(Canchita.PruebasUnitarias.TransaccionWS.Usuario usuario) {
            return base.Channel.ValidarUsuarioAsync(usuario);
        }
        
        public System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarifa> ListarTarifas(System.DateTime fechaReserva) {
            return base.Channel.ListarTarifas(fechaReserva);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarifa>> ListarTarifasAsync(System.DateTime fechaReserva) {
            return base.Channel.ListarTarifasAsync(fechaReserva);
        }
        
        public bool AgregarReserva(Canchita.PruebasUnitarias.TransaccionWS.Reserva reserva, System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.DetalleReserva> listaDetalle) {
            return base.Channel.AgregarReserva(reserva, listaDetalle);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarReservaAsync(Canchita.PruebasUnitarias.TransaccionWS.Reserva reserva, System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.DetalleReserva> listaDetalle) {
            return base.Channel.AgregarReservaAsync(reserva, listaDetalle);
        }
        
        public double retornarMontoReserva(int idReserva) {
            return base.Channel.retornarMontoReserva(idReserva);
        }
        
        public System.Threading.Tasks.Task<double> retornarMontoReservaAsync(int idReserva) {
            return base.Channel.retornarMontoReservaAsync(idReserva);
        }
        
        public bool crearTarjetas(Canchita.PruebasUnitarias.TransaccionWS.Tarjeta tarjeta) {
            return base.Channel.crearTarjetas(tarjeta);
        }
        
        public System.Threading.Tasks.Task<bool> crearTarjetasAsync(Canchita.PruebasUnitarias.TransaccionWS.Tarjeta tarjeta) {
            return base.Channel.crearTarjetasAsync(tarjeta);
        }
        
        public bool abonarSaldo(Canchita.PruebasUnitarias.TransaccionWS.Tarjeta tarjeta) {
            return base.Channel.abonarSaldo(tarjeta);
        }
        
        public System.Threading.Tasks.Task<bool> abonarSaldoAsync(Canchita.PruebasUnitarias.TransaccionWS.Tarjeta tarjeta) {
            return base.Channel.abonarSaldoAsync(tarjeta);
        }
        
        public System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta> listarTarjetas() {
            return base.Channel.listarTarjetas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta>> listarTarjetasAsync() {
            return base.Channel.listarTarjetasAsync();
        }
        
        public System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta> ObtenerTarjetasXUsuario(int id) {
            return base.Channel.ObtenerTarjetasXUsuario(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta>> ObtenerTarjetasXUsuarioAsync(int id) {
            return base.Channel.ObtenerTarjetasXUsuarioAsync(id);
        }
        
        public Canchita.PruebasUnitarias.TransaccionWS.Tarjeta obtenerTarjeta(string idTarjeta) {
            return base.Channel.obtenerTarjeta(idTarjeta);
        }
        
        public System.Threading.Tasks.Task<Canchita.PruebasUnitarias.TransaccionWS.Tarjeta> obtenerTarjetaAsync(string idTarjeta) {
            return base.Channel.obtenerTarjetaAsync(idTarjeta);
        }
        
        public bool pagarReservaConTarjeta(Canchita.PruebasUnitarias.TransaccionWS.Pago pago, string nroTarjeta, int idReserva) {
            return base.Channel.pagarReservaConTarjeta(pago, nroTarjeta, idReserva);
        }
        
        public System.Threading.Tasks.Task<bool> pagarReservaConTarjetaAsync(Canchita.PruebasUnitarias.TransaccionWS.Pago pago, string nroTarjeta, int idReserva) {
            return base.Channel.pagarReservaConTarjetaAsync(pago, nroTarjeta, idReserva);
        }
        
        public System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Pago> listarPagosPendientes() {
            return base.Channel.listarPagosPendientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Pago>> listarPagosPendientesAsync() {
            return base.Channel.listarPagosPendientesAsync();
        }
        
        public System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Pago> listarPagosCancelados() {
            return base.Channel.listarPagosCancelados();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Pago>> listarPagosCanceladosAsync() {
            return base.Channel.listarPagosCanceladosAsync();
        }
        
        public bool AgregarSede(Canchita.PruebasUnitarias.TransaccionWS.Sede sede) {
            return base.Channel.AgregarSede(sede);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarSedeAsync(Canchita.PruebasUnitarias.TransaccionWS.Sede sede) {
            return base.Channel.AgregarSedeAsync(sede);
        }
        
        public bool ActualizarSede(Canchita.PruebasUnitarias.TransaccionWS.Sede sede) {
            return base.Channel.ActualizarSede(sede);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarSedeAsync(Canchita.PruebasUnitarias.TransaccionWS.Sede sede) {
            return base.Channel.ActualizarSedeAsync(sede);
        }
        
        public System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Sede> ListarSedes() {
            return base.Channel.ListarSedes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Sede>> ListarSedesAsync() {
            return base.Channel.ListarSedesAsync();
        }
        
        public bool EliminarSede(Canchita.PruebasUnitarias.TransaccionWS.Sede sede) {
            return base.Channel.EliminarSede(sede);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarSedeAsync(Canchita.PruebasUnitarias.TransaccionWS.Sede sede) {
            return base.Channel.EliminarSedeAsync(sede);
        }
        
        public bool AgregarCampo(Canchita.PruebasUnitarias.TransaccionWS.Campo campo) {
            return base.Channel.AgregarCampo(campo);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarCampoAsync(Canchita.PruebasUnitarias.TransaccionWS.Campo campo) {
            return base.Channel.AgregarCampoAsync(campo);
        }
        
        public bool ActualizarCampo(Canchita.PruebasUnitarias.TransaccionWS.Campo campo) {
            return base.Channel.ActualizarCampo(campo);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCampoAsync(Canchita.PruebasUnitarias.TransaccionWS.Campo campo) {
            return base.Channel.ActualizarCampoAsync(campo);
        }
        
        public System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Campo> ListarCampos() {
            return base.Channel.ListarCampos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Canchita.PruebasUnitarias.TransaccionWS.Campo>> ListarCamposAsync() {
            return base.Channel.ListarCamposAsync();
        }
        
        public bool EliminarCampo(Canchita.PruebasUnitarias.TransaccionWS.Campo campo) {
            return base.Channel.EliminarCampo(campo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCampoAsync(Canchita.PruebasUnitarias.TransaccionWS.Campo campo) {
            return base.Channel.EliminarCampoAsync(campo);
        }
    }
}
